"""Package the current, compiled article without changing manuscript sources."""
from pathlib import Path
import hashlib
import json
import shutil
import subprocess
import zipfile

root = Path(__file__).resolve().parents[1]
out = root / 'agt_submission/final_upload'
out.mkdir(exist_ok=True)
sources = {Path('vr_st.tex'), Path('aux/bibliography.bib')}
for line in (root / 'vr_st.fls').read_text().splitlines():
    if not line.startswith('INPUT '):
        continue
    path = Path(line[6:])
    resolved = (root / path).resolve()
    if resolved.is_relative_to(root) and resolved.suffix in {'.tex', '.sty', '.cls', '.png', '.jpg', '.eps', '.pdf'}:
        sources.add(resolved.relative_to(root))
sources.add(Path('vr_st.bbl'))
with zipfile.ZipFile(out / 'article_sources.zip', 'w', zipfile.ZIP_DEFLATED) as archive:
    for path in sorted(sources):
        archive.write(root / path, path.as_posix())
    archive.writestr('BUILD.txt', 'Main file: vr_st.tex\nCompile with: pdflatex vr_st; biber vr_st; pdflatex vr_st; pdflatex vr_st\nAlternatively: latexmk -pdf vr_st.tex\nBibliography uses biblatex with Biber. The .bib and compiled .bbl are included.\nFigures are generated by the included TikZ/PGF LaTeX sources.\n')
shutil.copy2(root / 'vr_st.pdf', out / 'article.pdf')
manifest = {
    'accepted_commit': '6e23f50a836f2437f624fc83c1c04cf8bfd0df53',
    'current_commit': subprocess.check_output(['git', 'rev-parse', 'HEAD'], cwd=root, text=True).strip(),
    'source_sha256': {str(p): hashlib.sha256((root / p).read_bytes()).hexdigest() for p in sorted(sources)},
    'upload_sha256': {name: hashlib.sha256((out / name).read_bytes()).hexdigest() for name in ['article.pdf', 'change_list.txt', 'article_sources.zip']},
}
(out / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
print(f'Packaged {len(sources)} source files in {out}')
